// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("YAPSIT")>]
[<assembly: AssemblyProductAttribute("YAPSIT")>]
[<assembly: AssemblyDescriptionAttribute("yet another ProjectScaffold initialization test")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "YAPSIT"
    let [<Literal>] AssemblyProduct = "YAPSIT"
    let [<Literal>] AssemblyDescription = "yet another ProjectScaffold initialization test"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
